version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_PASSWORD: "pg123"
    ports:
      - "5432:5432"

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "a@a.com"
      PGADMIN_DEFAULT_PASSWORD: "pg123"
    ports:
      - "15432:80"
    depends_on:
      - postgres
