version: '2'

services:
  mongodb-dev-primary:
    image: 'bitnami/mongodb:latest'
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/bitnami
    environment:
      - MONGODB_ADVERTISED_HOSTNAME=containers-us-west-142.railway.app
      - MONGODB_USERNAME=mongo
      - MONGODB_PASSWORD=dN3c5JbuKSKbgaGIIt1Q
      - MONGODB_DATABASE=db1
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_ROOT_PASSWORD=rootpass1
      - MONGODB_REPLICA_SET_KEY=replicasetkey123
      - MONGODB_REPLICA_SET_NAME=rs1